 # libraries

library(XLConnect)
library(lubridate)
library(ordinal)
require(xtable)
require(knitr)
library(psych)
library(mlogit)
library(nnet)
library(MASS)
library(class)
library(lme4)
library(lsr)
require(effsize)
library(vcdExtra)
library(Kendall)
