---
title: "Untitled"
output:
  pdf_document: default
  # toc: yes
  #   toc_depth: 3
  #   number_sections: yes
  # ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE, warning = FALSE,fig.height=2.5)
source("libraries.R")
load(".RData")
my_report <- function(...) {

  fmt <- rmarkdown::pdf_document(...)

  fmt$knitr$knit_hooks$size = function(before, options, envir) {
    if (before) return(paste0("\n \\", options$size, "\n\n"))
    else return("\n\n \\normalsize \n")
  }

  return(fmt)
}
```

# Summary...

718 girls, 388 boys. Respondents FB 406, IG 192, SC 508. Had digital education 298, did not have digital education 898. Q9 FB and IG have been inverted. All factor levels are of the form $1...n$ with 1 been disagreement and $n$ agreement. The Shinyapp needs a small fix to ensure better distribution of users between the three different surveys.


# The data

```{r,size="tiny"}
cor(fbnum[,c(5,10,11:24)])
cor(ignum[,c(5,10,11:24)])
cor(scnum[,c(5,10,11:24)])
```
